services:
  bind-test:
    build:
      context: .
    container_name: bind-test
    ports:
      - 8053:53
    image: ghcr.io/hyper-w/rocky-bind-test/bind-test
    hostname: bind-test
    volumes:
    # - type: bind
    #   source: /sys/fs/cgroup
    #   target: /sys/fs/cgroup
    #   read_only: true
    - type: bind
      source: ./named/named.conf
      target: /etc/named.conf
    - type: bind
      source: ./named/named
      target: /etc/sysconfig/named
    - type: bind
      source: ./named/zones.conf
      target: /etc/named/zones.conf
    - type: bind
      source: ./named/bind-test.zone
      target: /etc/named/bind-test.zone
    - type: bind
      source: ./named/76.250.142.in-addr.arpa.conf
      target: /etc/named/76.250.142.in-addr.arpa.conf
    - type: bind
      source: ./named/76.250.142.in-addr.arpa.zone
      target: /etc/named/76.250.142.in-addr.arpa.zone
    # privileged: true
    # cap_add:
    #   - "SYS_ADMIN"
    networks:
      bind-test:
        ipv4_address: 172.31.0.2

networks:
    bind-test:
      name: bind-test
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.31.0.0/30