services:
  bind-test:
    build:
      context: .
    container_name: bind-test
    ports:
      - 8053:53
    image: bind-test
    hostname: bind-test
    volumes:
    - type: bind
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      read_only: true
    - type: bind
      source: ./named/named.conf
      target: /etc/named.conf
    - type: bind
      source: ./named/named
      target: /etc/sysconfig/named
    privileged: true
    # cap_add:
    #   - "SYS_ADMIN"
