name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
    docker_build_push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Login ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker Compose Build
              run: docker compose build nfs-server
            - name: Docker Compose Push
              run: docker compose push nfs-server